
# ---- PATIENT-DEPLOY -----
#EXPOSE PORT -- 8080

apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: patient-app
  name: patient-app
  namespace: dynamo
spec:
  replicas: 1 #CHANGE
  minReadySeconds: 45
  selector:
    matchLabels:
      app: patient-app
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: patient-app
    spec:
      containers:
       - env:
        - name: service-app-url
          value: 0.0.0.0
      - name: patient-app
        image: iamsandeep82/patient-app
        imagePullPolicy: IfNotPresent
        ports:
        - name: liveness-port
          containerPort: 8080
        resources: #CHANGE
          requests:
            cpu: 100m
            memory: 512Mi
          limits:
            cpu: 500m
            memory: 1024Mi #256Mi 
        readinessProbe:
          httpGet:
            path: /
            port: liveness-port
          failureThreshold: 5
          periodSeconds: 10
          initialDelaySeconds: 60
        livenessProbe:
          httpGet:
            path: /
            port: liveness-port
          failureThreshold: 5
          periodSeconds: 10
          initialDelaySeconds: 60
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
---
apiVersion: v1
kind: Service
metadata:
  name: patient-LB-service
  namespace: dynamo
  labels: #PODS
    app: patient-app
spec:
  ports:
  - # nodePort: 30702 #CHANGE
    port: 80 #CHANGE
    protocol: TCP
    targetPort: 8080 #CHANGE
  selector:
    app: patient-app
  sessionAffinity: None #CHANGE
  type: LoadBalancer
